### ISSUE TITLE
Standard Frameworks iOS template

### ISSUE THREAD

**Issue by casper91** [amirrajan/rubymotion-applied#101]
It seems like there are some standard frameworks that are loaded using [ios-template](https://github.com/amirrajan/rubymotion-templates/blob/master/motion/project/template/ios/config.rb#L39)

Perhaps this should be more explicit in the in the `Rakefile` of the project? 

Maybe you don't want some of them (maybe they have to be there in order to work). 

However while hacking I just kept thinking, why didn't I need to add those frameworks? (well they were defaults) 

When do I use a frameworks not included in the defaults?

**Comment by astechishin** [comment]
What frameworks do you believe are unneeded by most apps?

I usually find the docs tell me when I need to add a framework (such as CoreData or CloudKit or AVKit)

**Comment by casper91** [comment]
My concern was more, instead of the `Rakefile` containing:
```Ruby
# 5. If you need to reference any additional iOS libraries, use the config array below.
# ===========================================================================================
# app.frameworks << "StoreKit"
```
It could say something like:
```Ruby
# 5. If you need to reference any additional iOS libraries, use the config array below.
# ===========================================================================================
# Default's ['UIKit', 'Foundation', 'CoreGraphics', 'CoreFoundation', 'CFNetwork', 'CoreAudio']
# app.frameworks << "StoreKit"
```
Because I was using a lot of UIKit stuff and couldn't figure out why it worked without me adding it to the frameworks. Until I found them in the template.

**Comment by amirrajan** [comment]
@casper91 PR welcome. Just change this line: https://github.com/amirrajan/rubymotion-templates/blob/master/motion/project/template/ios/files/Rakefile.erb#L46

**Comment by casper91** [comment]
Has been merged: https://github.com/amirrajan/rubymotion-templates/commit/f2396af90be0c56bfa3f1c91eb70af919703b74a
