### ISSUE TITLE
Apple TV Simulator fails to run

### ISSUE THREAD

**Issue by astechishin** [amirrajan/rubymotion-applied#107]
When creating a new project (or recompiling an existing project) running rake is causing the tvOS 10 simulator to run even though the project is compiled with tvOS 11 or 12. The REPL then fails to connect to the simulator and the application crashes

**Comment by astechishin** [comment]
The hard-coded simulator name (line 111 in tvos.rb under templates) needs to change to "Apple TV" from "Apple TV 1080p"

**Comment by amirrajan** [comment]
This is fixed with the latest PR acceptance?

**Comment by astechishin** [comment]
Yes
