### ISSUE TITLE
Apple TV projects do not use new local templates directory

### ISSUE THREAD

**Issue by astechishin** [amirrajan/rubymotion-applied#108]
Apple TV projects need to use the local templates directory (located in: ~/.rubymotion/rubymotion-templates/motion/project)

**Comment by astechishin** [comment]
The Rakefile ERB template needs to add the line:
```
$:.unshift("~/.rubymotion/rubymotion-templates")
```
After line 2

**Comment by amirrajan** [comment]
This is fixed with the latest PR acceptance?

**Comment by astechishin** [comment]
Yes
