### ISSUE TITLE
RubyMotionSamples OSX Tweets link broken

### ISSUE THREAD

**Issue by dongyuwei** [amirrajan/rubymotion-applied#128]
on page of http://www.rubymotion.com/developers/samples/ , there is a [Tweets](https://github.com/HipByte/RubyMotionSamples/tree/master/osx/Tweets) samples, which is
 404 not found right now.

**Comment by AaronLasseigne** [comment]
It looks like it was removed because Twitter discontinued the API it was using. https://github.com/HipByte/RubyMotionSamples/commit/9ce391c9d8ba21b35b36ce4d3aea35defe26c282#diff-8e4f88e9d6ec0106ccc73b39d369c3e8

It should have been removed from the website as well.
