### ISSUE TITLE
Can't build a today extention with RM 5.0 and Xcode 9.0

### ISSUE THREAD

**Issue by katsuyoshi** [amirrajan/rubymotion-applied#23]
I'm trying to build my iOS App for iPhone X.
But I got an error for today extension.

Here is a build error.

```
Build today/build/iPhoneSimulator-11.0-Development
Compile today/app/today_view_controller.rb
Compile today/app/model/app_group_property.rb
rake aborted!
Can't locate kernel file
/Library/RubyMotion5.0/lib/motion/project/template/ios-extension-builder.rb:141:in `block (2 levels) in build'
/Library/RubyMotion5.0/lib/motion/project/template/ios-extension-builder.rb:138:in `each'
/Library/RubyMotion5.0/lib/motion/project/template/ios-extension-builder.rb:138:in `block in build'
/Library/RubyMotion5.0/lib/motion/project/parallel_builder.rb:47:in `block (2 levels) in initialize'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
    ERROR! Target './today' failed to build
```

I commented out ```app.target "./today", :extension``` in Rakefile.
Although It's included the watchapp target, build is success.

**Comment by katsuyoshi** [comment]
It seems to use an i386 architecture at  ios-extension-builder.rb:141.
Then it could not find a file "/Library/RubyMotion5.0/data/ios/11.0/iPhoneSimulator/kernel-i386.bc".
``` 
# ios-extension-builder.rb
archs.each do |arch|
　# Locate arch kernel.
　kernel = File.join(datadir, platform, "kernel-#{arch}.bc")
p kernel # => "/Library/RubyMotion5.0/data/ios/11.0/iPhoneSimulator/kernel-i386.bc"
　raise "Can't locate kernel file" unless File.exist?(kernel)
```

**Comment by amirrajan** [comment]
@katsuyoshi perfect, I'll get this updated (along with the other templates). Is this error completely block you from moving forward, or did you patch your RM rake files locally?

**Comment by amirrajan** [comment]
Also, you may want to explicitly set your architecture like so:

```ruby
app.archs['iPhoneOS'] = ['arm64']
```

**Comment by katsuyoshi** [comment]
@amirrajan thank you for your information.
I'm trying to submit with new environment. But I am not in a hurry.

I could build the app after adding ```app.archs['iPhoneOS'] = ['arm64']```.

But when I submitt, this message is appeared.

```
ERROR ITMS-90502: "Invalid Bundle. Apps that only contain the arm64 slice must also have 'arm64' in the list of UIRequiredDeviceCapabilities in Info.plist."
```

**Comment by amirrajan** [comment]
Add this too: 

```
app.info_plist['UIRequiredDeviceCapabilities'] = ['arm64']
```

**Comment by katsuyoshi** [comment]
Adding UIRequiredDeviceCapabilities is same result.

I added app.arches to root (iOS) Rakefile. Build is succeeded.
I added it to today target only, it seems to try armv7.

```
Compile today/app/today_view_controller.rb
"/Library/RubyMotion5.0/data/ios/11.0/iPhoneOS/kernel-arm64.bc"
   Compile today/app/model/app_group_property.rb
"/Library/RubyMotion5.0/data/ios/11.0/iPhoneOS/kernel-arm64.bc"
"/Library/RubyMotion5.0/data/ios/11.0/iPhoneOS/kernel-armv7.bc"
rake aborted!
Can't locate kernel file
/Library/RubyMotion5.0/lib/motion/project/template/ios-extension-builder.rb:142:in `block (2 levels) in build'
/Library/RubyMotion5.0/lib/motion/project/template/ios-extension-builder.rb:138:in `each'
/Library/RubyMotion5.0/lib/motion/project/template/ios-extension-builder.rb:138:in `block in build'
/Library/RubyMotion5.0/lib/motion/project/parallel_builder.rb:47:in `block (2 levels) in initialize'
```

Here is combinations I tried.
Left 3 column is combination of adding app.archs and UIRequiredDeviceCapabilities to Rakefile.
Right 4 columns are results.

| iOS | today | watchapp | => | build | upload | ios install | today widget | apple watch install |
|:--:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| o | - | - | | o | x | - | - | - |
| - | o | - | | x | - | - | - | - |
| o | - | o | | x | - | - | - | - |
| o | o | o | | o | o | o | x | x |

**Comment by amirrajan** [comment]
Related: https://github.com/amirrajan/rubymotion-applied/issues/24

**Comment by amirrajan** [comment]
@katsuyoshi can you make sure you've added 

```
app.info_plist['UIRequiredDeviceCapabilities'] = ['arm64']
app.archs['iPhoneOS'] = ['arm64']
```

to the parent app?

**Comment by katsuyoshi** [comment]
@amirrajan Yes I did except second line.

**Comment by amirrajan** [comment]
related to: https://github.com/amirrajan/rubymotion-applied/issues/24

**Comment by katsuyoshi** [comment]
@amirrajan It was solved today.

I had specified deployment_target in the parent app.

```
# Rakefile of parent app
app.deployment_target = '9.0'
```

I added it to the Rakefile of today target.

```
# Rakefile of today target
app.deployment_target = '9.0'
```

Then I could build the today target. Upload and installation succeeded.



I updated RM to version 5.2 today.
A build error message is changed.
I realized it is missing.

```
$ rake
     Build ./build/iPhoneSimulator-9.0-Development
     Build lib/objc
     Build vendor/TWSReleaseNotesView/TWSReleaseNotesView
     Build today/build/iPhoneSimulator-11.0-Development
   Compile today/app/model/app_group_property.rb
   Compile today/app/today_view_controller.rb
clang: error: invalid iOS deployment version '-mios-simulator-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
clang: error: invalid iOS deployment version '-mios-simulator-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
rake aborted!
```

**Comment by amirrajan** [comment]
🎉🎉

**Comment by katsuyoshi** [comment]
If deployment_target for today target is not specified, how about using parent values?
Or, always use the parent value.

**Comment by amirrajan** [comment]
If I recall correctly, for extensions, the parent value is always used (and extension value is ignored). If that is the case, I'll make sure to update the templates so that the user is notified more clearly.
