### ISSUE TITLE
Flurry Cocoapod + High Sierra + OSX 

### ISSUE THREAD

**Issue by amirrajan** [amirrajan/rubymotion-applied#40]
Figure out what’s causing this to not work

**Comment by forrestgrant** [comment]
Steps to reproduce: https://github.com/forrestgrant/cocoapods-high-sierra-bug

**Comment by amirrajan** [comment]
@forrestgrant could you try `env experimental_dependency=1 rake clean default` and see if that builds for you?

**Comment by amirrajan** [comment]
I was able to build and run on High Sierra + Xcode 9.0 + RM 5.3:

Rakefile:

```
app.pods do
  pod 'Flurry-iOS-SDK/FlurryAds'
end
```

`rake clean:all pod:install default`

```
>defined? FlurryAds
=>"constant"
```

Can you confirm @forrestgrant?
