### ISSUE TITLE
Sql Lite + Cocoa Pod + High Sierra + OSX

### ISSUE THREAD

**Issue by amirrajan** [amirrajan/rubymotion-applied#42]
No worky: https://github.com/eamonn-webster/TestMotionSQLite3

**Comment by victorcechinel** [comment]
See repo: https://github.com/solanoluz/motion-sqlite3

Gem file:
```
gem 'motion-sqlite3', git: 'git@github.com:solanoluz/motion-sqlite3.git'
gem 'motion-cocoapods', '1.8.1'
```

Add this code on Rakefile:

```
Motion::Project::App.setup do |app|
   # Last line
   app.libs << '/usr/lib/libsqlite3.dylib'
   app.include 'sqlite3.h'
end
```

**Comment by amirrajan** [comment]
@victorcechinel did you get this working on High Sierra? I'm still getting an error.

**Comment by amirrajan** [comment]
https://gist.github.com/amirrajan/5c2b9185bf431403309f2fc61cb163b1

**Comment by amirrajan** [comment]
This line needs to be fixed /cc @victorcechinel @kastiglione for HighSierra: https://github.com/amirrajan/motion.h/blob/master/lib/motion.h.rb#L71

@kastiglione, do you accept pull requests? Make me a collaborator and give me access to push motion.h?

**Comment by amirrajan** [comment]
Will open issue on motion.h or fork and deploy a new version.

**Comment by kastiglione** [comment]
I'm happy to add collaborators, also happy to hand off the project. If you fork I'll be sure to point the original repo to yours.

**Comment by amirrajan** [comment]
@kastiglione I’d be happy to take over. Mind adding me as a collaborator to your repo (and give me push rights for the gem)?

**Comment by ben5516** [comment]
@amirrajan What error were you getting with High Sierra? On my own app, I'm getting:

```bash
can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo={NSLocalizedDescription=zero length data}
```

but when I clone and build https://github.com/eamonn-webster/TestMotionSQLite3, it actually compiles and launches in the simulator, but I get this error:

```ruby
uninitialized constant SQLite3::Database::SQLITE_OK (NameError)
```

**Comment by kastiglione** [comment]
@amirrajan I added you as collaborator. I'll do the gem rights later today.

**Comment by kastiglione** [comment]
@amirrajan How do I add gem push rights, via gemspec?

**Comment by amirrajan** [comment]
I think through rubygems.org maybe?

**Comment by ben5516** [comment]
@amirrajan @kastiglione Were you ever able to get the gem pushed?

**Comment by Lax** [comment]
@kastiglione Use `gem owner <gem> -a <email>` command.
`gem help owner` for detail.

**Comment by amirrajan** [comment]
@ben5516 this week hopefully.

**Comment by kastiglione** [comment]
@ben5516 I looked to add @amirrajan as a gem owner via rubygems.org, but didn't see where to do that. Seems that's the only thing to do before @amirrajan can push an update.

**Comment by kastiglione** [comment]
oh I just saw @Lax's comment. I'll do that.

**Comment by kastiglione** [comment]
@amirrajan I have added you as an owner.

**Comment by ben5516** [comment]
Thanks @kastiglione

**Comment by amirrajan** [comment]
@ben5516 , updated. Mind confirming?

```
gem uninstall motion.h #uninstall 0.0.4
gem install motion.h #install 0.0.5
rake clean:all #navigate to your app and clean all
rm -rf ~/Library/RubyMotion #blow away any cached bridge support files
rake default #build and see if it works
```

**Comment by ben5516** [comment]
@amirrajan 

Worked for me!
