### ISSUE TITLE
motion-cocoapods + `.bundle` + `.resources`

### ISSUE THREAD

**Issue by amirrajan** [amirrajan/rubymotion-applied#47]
https://github.com/jgritman/motion-pods-test

**Comment by amirrajan** [comment]
https://github.com/HipByte/motion-cocoapods/blob/master/lib/motion/project/cocoapods.rb#L536-L537

https://github.com/HipByte/motion-cocoapods/blob/master/lib/motion/project/cocoapods.rb#L505

**Comment by amirrajan** [comment]
This is an update that will need to be made in motion-cocoapods (but I'll track it here)

**Comment by Lax** [comment]
I have similar problems.

the matched path has `${PODS_ROOT}` prefix,
```
## Pods-RubyMotion-resources.sh
  install_resource "${PODS_ROOT}/CSSSelectorConverter/CSSSelectorConverter/CSSSelectorGrammar.txt"
```


https://github.com/HipByte/motion-cocoapods/blob/master/lib/motion/project/cocoapods.rb#L510
```
resources << Pathname.new(@config.project_dir) + PODS_ROOT + path
```

so the file path in resources is  `#<Pathname:vendor/Pods/${PODS_ROOT}/CSSSelectorConverter/CSSSelectorConverter/CSSSelectorGrammar.txt>`

**Comment by amirrajan** [comment]
@Lax Mark is actually working on this issue this week.

**Comment by Lax** [comment]
This issue is included in `RM 5.6`?

**Comment by amirrajan** [comment]
Slated for 5.7

**Comment by amirrajan** [comment]
Had to release 5.6 because Apple made Xcode 9.2 GM.

Updated the milestone name: https://github.com/amirrajan/rubymotion-applied/milestone/3
