### ISSUE TITLE
macOS static constants NSAlertFirstButtonReturn, NSAlertSecondButtonReturn, NSAlertThirdButtonReturn not available

### ISSUE THREAD

**Issue by hboon** [amirrajan/rubymotion-applied#49]
These were available in an older version of RubyMotion (4.x or earlier probably).

Enums in the same file `NSAlert.h` are available, eg. `NSAlertStyleWarning`

I think there might have been an issue with static const in RubyMotion previously, not sure how it was handled.

```
Link ./build/MacOSX-10.9-Development/mLogger.app/Contents/MacOS/mLogger            
Undefined symbols for architecture x86_64:    
"_NSAlertFirstButtonReturn", referenced from:                                             
  _MREP_750A02BC00034E75BB4EF6E861E0BBA3 in app_delegate.rb.o                           
ld: symbol(s) not found for architecture x86_64                                             
```

**Comment by hboon** [comment]
This might give a clue:

If I define this:

module NSMissingConstants
  AlertFirstButtonReturn = 1000
  AlertSecondButtonReturn = 1001
  AlertThirdButtonReturn = 1002
end

Run the app, then I can access `NSAlertFirstButtonReturn` in the REPL.

**Comment by amirrajan** [comment]
Will be fixed in RM 5.4 (planning on releasing that this week).

Edit: wrote wrong version number.
Edit: Xcode 9.1 dropped just now. Rebuilding.

**Comment by digitalmoksha** [comment]
@amirrajan this is still failing for me, using RM 5.4

<img width="882" alt="screen shot 2017-11-06 at 1 25 06 pm" src="https://user-images.githubusercontent.com/20626/32441036-ffcfc898-c2f5-11e7-9d11-cfcfbe5fd420.png">

I have a sample project that demonstrates the issue:  https://github.com/digitalmoksha/rm_osx_test

**Comment by amirrajan** [comment]
@hboon is it failing for you still too?

**Comment by digitalmoksha** [comment]
This works now for me in RM 5.5.

**Comment by hboon** [comment]
@amirrajan working for me in 5.5. Thanks for the fix! (Sorry, just back from holidays).
