### ISSUE TITLE
Incorrect value for NSAppKitVersionNumber on macOS High Sierra...

### ISSUE THREAD

**Issue by digitalmoksha** [amirrajan/rubymotion-applied#59]
You can use `NSAppKitVersionNumber` to get the version of the AppKit you're running on (macOS), as well as compare it against constants for various appkit versions, such as `NSAppKitVersionNumber10_12_2`

On macOS 10.13.0, `NSAppKitVersionNumber` should equal `1561.0` - this is what is shown when running a sample app built with XCode.

RM 5.3 and 5.4 show  `NSAppKitVersionNumber` as `577.0`, which is equal to `NSAppKitVersionNumber10_0`, OS X 10.0

Here is a screen shot of printing those values with RM:

<img width="324" alt="screen shot 2017-11-06 at 1 34 13 pm" src="https://user-images.githubusercontent.com/20626/32441295-43118d8e-c2f7-11e7-8859-83784a72c7c2.png">

I have a sample project showing the issue, for both RM and XCode/Cocoa.  https://github.com/digitalmoksha/rm_osx_test

**Comment by amirrajan** [comment]
Making an update to BridgeSupport to explicitly wire up this constant correctly (it's a rare API collision).

I'll make sure that both 10.12 and 10.13 work using your sample project and get a release out.

**Comment by digitalmoksha** [comment]
ah cool, thank you...

**Comment by amirrajan** [comment]
Building now, expect a release tonight (November 8th).

Edit: November 9th. Running full regression first (messaged you on Slack).

**Comment by digitalmoksha** [comment]
Fixed in RM 5.5.  I verified the correct value is generated on 10.13, 10.12, and 10.11.  Thanks Amir!
